### ISSUE TITLE
Detection accuracy

### ISSUE THREAD

**Issue by onionysy** [Robertwyq/PanoOcc#10]
I see that you compared the detection accuracy in the ablation experiment of the paper, but the code did not test the detection accuracy during the testing process, may I ask if there is any open source code?

**Comment by onionysy** [comment]
we didn't see the "./projects/configs/PanoOcc/Panoptic/PanoOcc_small_4f.py" file

**Comment by Robertwyq** [comment]
@onionysy  I'm sorry that the previous code wasn't updated, it is now available.
