### ISSUE TITLE
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:911, invalid usage, NCCL version 2.7.8

### ISSUE THREAD

**Issue by Ha-coding-user** [Robertwyq/PanoOcc#11]
**Hi
In docker container, After completing the environment setting, I meet this error**

> [W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "./tools/train.py", line 256, in <module>
>   File "./tools/train.py", line 256, in <module>
>         main()
>   File "./tools/train.py", line 216, in main
> main()
>   File "./tools/train.py", line 216, in main
>     model.init_weights()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
>         model.init_weights()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
> m.init_weights()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
>     m.init_weights()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
>     initialize(self, self.init_cfg)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 612, in initialize
>     initialize(self, self.init_cfg)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 612, in initialize
>         _initialize(module, cp_cfg)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 517, in _initialize
> _initialize(module, cp_cfg)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 517, in _initialize
>     func(module)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 489, in __call__
>     func(module)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 489, in __call__
>     load_checkpoint(
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
>     load_checkpoint(
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
>     checkpoint = _load_checkpoint(filename, map_location, logger)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
>     checkpoint = _load_checkpoint(filename, map_location, logger)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
>     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
>     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
>     return checkpoint_loader(filename, map_location)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 390, in load_from_torchvision
>     return checkpoint_loader(filename, map_location)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 390, in load_from_torchvision
>     return load_from_http(model_urls[model_name], map_location=map_location)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 290, in load_from_http
>     return load_from_http(model_urls[model_name], map_location=map_location)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 290, in load_from_http
>     torch.distributed.barrier()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
>     torch.distributed.barrier()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:911, invalid usage, NCCL version 2.7.8
> ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:911, invalid usage, NCCL version 2.7.8
> ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23199) of binary: /root/anaconda3/envs/occ/bin/python
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/occ/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/anaconda3/envs/occ/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
>     main()
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
>     launch(args)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
>     run(args)
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
>     elastic_launch(
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/root/anaconda3/envs/occ/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

I think this error is related with NCCL, but I can't find solution
I use single GPU RTX 3080, and I just follow your install.md. So I, think all setting is same with your environment.

Please Reply me plz.
Thank you.

**Comment by Robertwyq** [comment]
@Ha-coding-user Sorry, I haven't encountered such an issue. Is this happening while running the training script? Could you please rerun your script with export NCCL_DEBUG=INFO and post the output here?

**Comment by Ha-coding-user** [comment]
@Robertwyq Hello, My reply is too late...
Now, I just wonder that environment of this project.

I am using Window10, and construct environment used Anaconda
and Just follow your Install.md

Please reply me...
Thank you.

**Comment by Robertwyq** [comment]
Hi @Ha-coding-user.
Our project works well on both Ubuntu 18 and Ubuntu 20 environments. 
Using Anaconda, CUDA11 or CUDA 12.
However, we haven't tested it on Windows, so there might be potential issues there.

**Comment by Ha-coding-user** [comment]
@Robertwyq  Hmm... Okay.
How about Docker Window?
Do you have any Dockerfile for release...?

**Comment by Ha-coding-user** [comment]
Hi @Robertwyq 
This is all of NCCL Error Log

1501f1b2f4c7:4089:4089 [0] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.2<0>
1501f1b2f4c7:4089:4089 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

1501f1b2f4c7:4089:4089 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
1501f1b2f4c7:4089:4089 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
1501f1b2f4c7:4089:4089 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda11.1

1501f1b2f4c7:4089:4483 [0] graph/xml.cc:332 NCCL WARN Could not find real path of /sys/class/pci_bus/0000:07/../../0000:07:00.0
1501f1b2f4c7:4089:4483 [0] NCCL INFO graph/xml.cc:469 -> 2
1501f1b2f4c7:4089:4483 [0] NCCL INFO graph/xml.cc:660 -> 2
1501f1b2f4c7:4089:4483 [0] NCCL INFO graph/topo.cc:523 -> 2
1501f1b2f4c7:4089:4483 [0] NCCL INFO init.cc:581 -> 2
1501f1b2f4c7:4089:4483 [0] NCCL INFO init.cc:840 -> 2
1501f1b2f4c7:4089:4483 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
Traceback (most recent call last):
  File "./tools/train.py", line 256, in <module>
    main()
  File "./tools/train.py", line 245, in main
    custom_train_model(
  File "/PanoOcc/projects/mmdet3d_plugin/bevformer/apis/train.py", line 27, in custom_train_model
    custom_train_detector(
  File "/PanoOcc/projects/mmdet3d_plugin/bevformer/apis/mmdet_train.py", line 75, in custom_train_detector
    model = MMDistributedDataParallel(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 496, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

I use DockerWindow and all of environment is same of your install.md

**Comment by Robertwyq** [comment]
Hi @Ha-coding-user, I don't have a clear solution to this problem at the moment. We will try setting up Docker environment on Windows.

**Comment by Ha-coding-user** [comment]
Hi @Robertwyq 
I find solution!
In Window OS, NCCL is not supported.
So We need to change NCCL to GLOO

This is solution to change NCCL to GLOO
> /PanoOcc/projects/configs/_base_/default_runtime.py
> dist_params = dict(backend='nccl') -> dist_params = dict(backend='gloo')

> /usr/local/envs/occ/lib/python3.8/site-packages/mmcv/runner/dist_utils.py
> def init_dist(launcher, backend='nccl', **kwargs) -> def init_dist(launcher, backend='gloo', **kwargs)

Thank you for your effort to find solution.
I close this issue
