### ISSUE TITLE
Where can I download the weights for PanoOcc-Large-T?

### ISSUE THREAD

**Issue by danilotpnta** [Robertwyq/PanoOcc#13]
Hi, in the comparison Table 1 you are mentioning you are using PanoOcc-Large-T, however from the guide I cannot see where can I download this model. Could you update documentation. 

Great work guys, thank you.

**Comment by Robertwyq** [comment]
@danilotpnta  Hi, I am sorry for the delay in responding. We have updated the large checkpoint and configuration.
