### ISSUE TITLE
camera_mask

### ISSUE THREAD

**Issue by Yzichen** [Robertwyq/PanoOcc#3]
Some of the previous methods didn't use camera_mask during training, but used it during eval, right?

**Comment by Robertwyq** [comment]
> Some of the previous methods didn't use camera_mask during training, but used it during eval, right?

For occupancy prediction task, previous methods didn't use camera_mask during training but used it during evaluation. Recent performance like BEVFormer*(39.24) and BEVDet(42.02) used it during training.
