### ISSUE TITLE
Question about the align_prev_bev

### ISSUE THREAD

**Issue by supersenyun** [Robertwyq/PanoOcc#5]
https://github.com/Robertwyq/PanoOcc/blob/ce36b10f0d1ec8b155d291a2dccf5c9907beff8e/projects/mmdet3d_plugin/bevformer/modules/pano_transformer_occ.py#L205

I want to know if there is a problem here? Shouldn't it be from below

```
 for i in range(bs):
                lidar_to_ego = kwargs[i]['lidar2ego_transformation']
                curr_ego_to_global = kwargs[i]['ego2global_transform_lst'][-1]
                curr_lidar_to_global = curr_ego_to_global @ lidar_to_ego
                curr_grid_in_prev_frame_lst = []
                for j in range(len_queue):
                    prev_ego_to_global = kwargs[i]['ego2global_transform_lst'][j]
                    prev_lidar_to_global = prev_ego_to_global @ lidar_to_ego

                    prev_lidar_to_curr_lidar =  np.linalg.inv(curr_lidar_to_global) @ prev_lidar_to_global 
                    curr_lidar_to_prev_lidar = np.linalg.inv(prev_lidar_to_curr_lidar)

```

**Comment by Robertwyq** [comment]
I'm sorry for not replying to you in time. Regarding your question, it seems to be a naming issue.  Actually, the "nuscenes-occ" benchmark uses the ego-coordinate, so the temporal transformation should be calculated between egos. However, the variable names are borrowed from the LiDAR system's naming convention, which may have caused some misunderstanding for you.
