### ISSUE TITLE
Testing with a single GPU

### ISSUE THREAD

**Issue by 1447918335** [Robertwyq/PanoOcc#7]
May I ask what changes I need to make to the code when testing with a single GPU？

**Comment by Robertwyq** [comment]
Hi, @1447918335 , change the gpu number 8 to 1 is ok.
For example:
./tools/dist_test_dense.sh ./projects/configs/PanoOcc/Occupancy/Occ3d-nuScenes/PanoOcc_small.py work_dirs/PanoOcc_small/epoch_24.pth 1

**Comment by 1447918335** [comment]
Thanks！I'll close this issue.
